apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-terminate-gw
  namespace: web
spec:
  addresses:
  - type: "IPAddress"
    value: 192.168.48.202
  gatewayClassName: f5-gateway-class
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: local-test-tls-cert
        namespace: sec-infra
        kind: Secret
        group: ""
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-terminate-http-route
  namespace: web
spec:
  parentRefs:
  - name: tls-terminate-gw
    sectionName: https
  hostnames:
  - www.f5bnk.com
  rules:
  - backendRefs:
    - name: httpbin
      port: 8080
