[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = US
ST = California
L = Seattle
O = F5 Rabbit
OU = F5 Rabbit
CN = rabbitmq-server.default.svc.cluster.local

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = rabbitmq-server.default.svc.cluster.local
DNS.2 = rabbitmq-server.default
DNS.3 = rabbitmq-server.default.svc
