apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs-pv
  namespace: f5-bnk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.47.242
    path: "/srv/nfs/bnk"
  mountOptions:
    - nfsvers=3
    - hard
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: f5-bnk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: prometheus-nfs-pv
  storageClassName: ""