apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: l4route-tcp1-gw
  namespace: web
spec:
  addresses:
  - type: "IPAddress"
    value: 192.168.48.211 
  gatewayClassName: f5-gateway-class 
  listeners:
  - name: nginx
    protocol: TCP
    port: 80
    allowedRoutes:
      kinds:
      - kind: L4Route
        group: gateway.k8s.f5net.com
---
apiVersion: gateway.k8s.f5net.com/v1
kind: L4Route
metadata:
  name: l4route-tcp1-app
  namespace: web 
spec:
  protocol: TCP
  parentRefs:
  - name: l4route-tcp1-gw 
    sectionName: nginx
  rules:
  - backendRefs:
    - name: web-nginx-svc 
      namespace: web 
      port: 80
