apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "f5-lifecycle-operator.labels" . | nindent 4 }}
  name: {{ template "f5-lifecycle-operator.serviceAccountName" . }}
  namespace: {{ include "f5-lifecycle-operator.namespace" . }}
# secrets:
#   - name: far-secret
