apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: l4-udp-gw
  namespace: web
spec:
  addresses:
  - type: "IPAddress"
    value: 192.168.48.202
  gatewayClassName: f5-gateway-class
  listeners:
  - name: anyudp
    protocol: UDP
    port: 12345
    allowedRoutes:
      kinds:
      - kind: L4Route
        group: gateway.k8s.f5net.com
---
apiVersion: gateway.k8s.f5net.com/v1
kind: L4Route
metadata:
  name: l4-udp-app
  namespace: web
spec:
  protocol: UDP
  parentRefs:
  - name: l4-udp-gw
    sectionName: anyudp
  rules:
  - backendRefs:
    - name: udp-echo-service
      namespace: web
      port: 12345