authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = rabbitmq-server.default.svc.cluster.local
DNS.2 = rabbitmq-server.default
DNS.3 = rabbitmq-server.default.svc
