apiVersion: k8s.f5.com/v1
kind: BNKManifest
metadata:
  name: bigip-k8s-manifest-2.1.0-3.1736.1-0.1.27
spec:
  images:
  - name: cert-manager-cainjector
    version: v2.3.0
  - name: cert-manager-controller
    version: v2.3.0
  - name: cert-manager-startupapicheck
    version: v2.3.0
  - name: cert-manager-webhook
    version: v2.3.0
  - name: crd-conversion
    version: v1.69.3-0.0.5
  - name: crdupdater
    version: v0.4.32-0.0.2
  - name: f5-blobd
    version: v1.23.1-0.0.5
  - name: f5-cert-client
    version: v3.1.2-0.0.3
  - name: f5-csm-qkview
    version: v0.10.37-0.0.4
  - name: f5-debug-sidecar
    version: v10.5.0-0.1.32
  - name: f5-downloader
    version: v0.27.9-0.0.12
  - name: f5-dssm-store
    version: v5.1.7-0.0.3
  - name: f5-dssm-upgrader
    version: v2.0.17-0.0.3
  - name: f5-fluentbit
    version: v1.2.8-0.0.5
  - name: f5-fluentd
    version: v2.0.11-0.0.11
  - name: f5-l4p-engine
    version: v1.127.13-0.0.5
  - name: f5-license-helper
    version: v0.12.10-0.0.4
  - name: f5-nsec-ips-daemon
    version: v3.5.1-0.0.4
  - name: f5-toda-tmstatsd
    version: v1.11.19-0.0.3
  - name: f5dr-img
    version: v3.2.14-0.0.4
  - name: f5dr-img-init
    version: v3.2.14-0.0.4
  - name: f5ing-tmm-pod-manager
    version: v1.0.18-0.0.7
  - name: f5ingress
    version: v13.7.1-0.3.19
  - name: init-certmgr
    version: v0.23.35-0.0.10
  - name: opentelemetry-collector-contrib
    version: 0.123.0
  - name: rabbit
    version: v0.5.9-0.0.11
  - name: spk-cwc
    version: v0.35.0-0.0.5
  - name: tmm-img
    version: v10.50.7-0.2.7
  - name: tmrouted-img
    version: v2.3.0-0.0.3
  - name: spk-csrc
    version: v0.6.1-0.0.5
  - name: f5-dwbld
    version: v1.161.0-0.2.9
  - name: f5-coremond
    version: v0.7.56-0.0.5
  - name: f5-toda-observer
    version: v5.7.5-0.1.0
  - name: f5-bdosd
    version: v0.72.0-0.1.3
  - name: dnsx-img
    version: v0.10.21-0.0.4
  - name: f5-lifecycle-operator
    version: v1.198.4-0.1.36
  - name: f5-ipam-controller
    version: v1.1.35-0.0.6
  - name: f5-node-labeler
    version: v0.0.15-0.0.2
  - name: f5-eowyn-install
    version: v0.5.4
  - name: crd-installer
    version: v13.7.1-0.3.19
  - name: postgresql
    version: 17.5.0
  - name: vault
    version: 1.20.1
  - name: vault-init
    version: 1.29.0-0.10.12
  - name: f5-license-proxy
    version: 1.29.0-0.10.12
  - name: f5-env-discovery
    version: v1.198.4-0.1.36
  - name: f5-fqdn-resolver
    version: v0.8.1-0.0.3
  - name: gslb-engine
    version: v0.111.15-0.0.2
  - name: gslb-probe-agent
    version: v0.31.4-0.0.2
  - name: f5-analyzer
    version: v0.0.3-0.0.5
  version: 2.1.0-3.1736.1-0.1.27  
